### ISSUE TITLE
write some unit tests

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/java-app-sdk#29]
This will require persistent dev credentials that we could use as environment vars to run real tests on the account API:
* [ ] Account
* [ ] Data-AMQP
* [ ] Data-MQTT
* [ ] Management

**Comment by FokkeZB** [comment]
For MQTT and AMQP you could use a public broker. See the tests in the NodeJS SDK

**Comment by makowskimateusz** [comment]
@cambierr Maybe i will try to add some unit tests in my free time, what do you things about it?

**Comment by cambierr** [comment]
@makowskimateusz this would be great !
