### ISSUE TITLE
Setup travis auto-deployment to sonatype

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/java-app-sdk#32]

**Comment by FokkeZB** [comment]
Any suggestions? ☺️

**Comment by cambierr** [comment]
Well, I prepared everything :)

Now the travis build needs the signing key (encrypted!) + you to set the environments variables that I prepared in https://github.com/TheThingsNetwork/java-app-sdk/blob/2.0.0/settings.xml

Using that, we should be able to have it working. The last thing I will have to de once your signing key is in the repo (or somewhere we can download it from travis) is write some bash lines that will import it into gpg before the build actually starts.

Do you think it's good enough ?

**Comment by cambierr** [comment]
I'm updating the repo according to: https://github.com/making/travis-ci-maven-deploy-skelton
This means you'll have to set env vars accordingly, as well as put your encrypted keys inside the repo
