### ISSUE TITLE
Generate JavaDoc and host it via GitHub Pages

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/java-app-sdk#33]
If you generate it to `/docs` we can enable GitHub Pages on that folder so that it will be available via https://thethingsnetwork.github.io/java-app-sdk/

**Comment by cambierr** [comment]
Ideally this should be done by travis also.
Do you know an easy way for travis to commit the doc to master when performing releases ?

**Comment by cambierr** [comment]
Well, I managed to automate the documentation upload to the branh gh-pages ;-)

**Comment by cambierr** [comment]
Env vars required:
* GH_TOKEN : a personal access token with repo rights
* GH_REF : the repo path. github.com/TheThingsNetwork/java-app-sdk.git in our case

**Comment by FokkeZB** [comment]
both set: https://travis-ci.org/TheThingsNetwork/java-app-sdk/settings
