### ISSUE TITLE
Write docs for all components

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/java-app-sdk#45]

**Comment by matthiaszimmermann** [comment]
i am trying to get the sample applications running. thanks to the documentation for the mqtt sample [1] it looks as if i got this one [2] working. 

as a next step i'd like to get the management [3] and the account samples [4] running. so far i am assuming that i can reuse the values for applicationId (= "appId" from mqtt sample?) and applicationKey (= "accessKey" from mqtt sample?). however, i was not able to figure out what values to provide for the variables "clientId" and "clientSecret". could you please provide pointers as availabe for the mqtt sample? (ie. which values to copy from the things network console)

thanks!


[1] https://www.thethingsnetwork.org/docs/applications/java/quick-start.html#connect
[2] org.thethingsnetwork.samples.mqtt.App
[3] org.thethingsnetwork.samples.management.App
[4] org.thethingsnetwork.samples.account.App

**Comment by cambierr** [comment]
You should use ApplicationAccessKey as grant type (or the async version). Only that grant type is supported by non-integrated applications. Others requires you to register a developer app at The Things Network ;-)
