### ISSUE TITLE
database integration support

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/java-app-sdk#52]
This as been requested several times on the slack channel.

Do you ( @htdvisser @johanstokking) think this could be a good idea ?

If so, should this be data-http ? or a subpart of the device management endpoint ?

**Comment by htdvisser** [comment]
I'm not sure if this belongs in the sdk, as the data integration is an external integration that does not fall under The Things Network Foundation. Just like the IFTTT and MyDevices integrations don't belong in the SDK, the data integration doesn't belong here either.

Nothing stops you from building this in a separate project though

**Comment by cambierr** [comment]
What would be the best way ?

A group of projects like `org.thethingsnetwork.integration.*` (integrations built by ttn) and `org.thethingsnetwork.integration.database` in our case (to make them easier to find for users) ?

**Comment by johanstokking** [comment]
Yes, I would have these as community projects for now. We need to see what belongs where, also considering who hosts it where and does operations. Also, there's already the data storage integration, but I can imagine your idea is to write directly to a database.

**Comment by cambierr** [comment]
So, what I suggest is to do something similar to spring-data project for instance where any database developer (or community member) can add a sub-project containing stuff related to their database.

In our case, this would mean a "java-integration-sdk" repository with different subprojects as `org.thethingsnetwork.integration.*`folders.

My idea is not about writing anything anywhere but several people already asked for a "database integration" sdk in java to avoid having to rewrite the query code :)

Can we imagine this `java-integration-sdk` repo ?
