### ISSUE TITLE
SDK's Java gRPC Client not using TLS?

### ISSUE THREAD

**Issue by FlorianCodes** [TheThingsNetwork/java-app-sdk#59]
Referring to [1], is the Java gRPC client provided in the SDK **not using TLS**?
If so, when can a fix be expected?
If not, help for solving the problem explained in [1] is appreciated.

[1] https://www.thethingsnetwork.org/forum/t/encountering-problems-using-java-sdk-authenticating-with-an-access-key-http2exception/13200

**Comment by naveen-25** [comment]
Added TLS as an option in version 2.1.3

**Comment by naveen-25** [comment]
> Referring to [1], is the Java gRPC client provided in the SDK **not using TLS**?
> If so, when can a fix be expected?
> If not, help for solving the problem explained in [1] is appreciated.
> 
> [1] https://www.thethingsnetwork.org/forum/t/encountering-problems-using-java-sdk-authenticating-with-an-access-key-http2exception/13200

Added TLS as an option in version 2.1.3
