### ISSUE TITLE
Only OTAA devices Events are Received, not ABP

### ISSUE THREAD

**Issue by erberj** [TheThingsNetwork/java-app-sdk#66]
I started the mqtt sample. I have about 7 devices registered in TTN 2 of them OTAA activated, the others ABP. When I run the example, it connects successfully to ttn but only messages of OTAA devices appear in the trace.

**Comment by johanstokking** [comment]
@erberj the reason is probably that the session keys are wrong or, most likely, the frame counters are reset. You may want to try in the Console the button to reset frame counters.

This is not related to the Java SDK, so I'm closing this issue.
